### ISSUE TITLE
Targeting `wasm32-wasi`

### ISSUE THREAD

**Issue by rvolosatovs** [bytecodealliance/registry#1]
Is being able to target `wasm32-wasi` a desirable design goal?
At least from the perspective of dog fooding - what better way to validate the WASI API design, than to implement a production-grade networked service with persistent storage that works as a WASM module? This could also then serve as a reference implementation of a "best practices" service designed from scratch for WASI capability-based access model.

If this is indeed something we want, then it is most probably a good idea to adopt [`cap-async-std`](https://docs.rs/cap-async-std/latest/cap_async_std/index.html) and [`async-std`](https://docs.rs/async-std/1.12.0/async_std/index.html), which it is build upon sooner, rather than later.

**Comment by calvinrp** [comment]
Cleaning up old issues
