### ISSUE TITLE
warg-server Args no-such-field without postgres feature

### ISSUE THREAD

**Issue by kriswuollett** [bytecodealliance/registry#106]
Visual Studio Code displays `no such fieldrust-analyzer[no-such-field](https://rust-analyzer.github.io/manual.html#no-such-field)` on the following when feature `postgres` is not included in analyzer settings:

https://github.com/bytecodealliance/registry/blob/72a904990175a07853f4b96c3df2defd7ede1e14/crates/server/src/bin/warg-server.rs#L17

```jsonc
{
    // "rust-analyzer.cargo.features": ["postgres"],
}
```

![CleanShot 2023-05-05 at 13 17 04@2x](https://user-images.githubusercontent.com/1834192/236537003-bbddbe88-fe5c-49de-8985-e09c19ace2b9.png)

The error goes away when the `database_url` and `database_url_file` fields are commented out:

https://github.com/bytecodealliance/registry/blob/72a904990175a07853f4b96c3df2defd7ede1e14/crates/server/src/bin/warg-server.rs#L35-L48

**Comment by kriswuollett** [comment]
Perhaps another false positive like https://github.com/rust-lang/rust-analyzer/issues/11473

**Comment by peterhuene** [comment]
Merged the workaround, so I think we can close this for now.
