### ISSUE TITLE
Story: search for a package in the registry

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/registry#11]
[Story link](https://github.com/bytecodealliance/SIG-Registries/blob/main/docs/user-stories.md#discovering-components-d-e-t)

This is a story issue to track the overall progress towards achieving a user story.

Tasks:

* [x] #31 
* [ ] #35 
* [ ] #33 
* [ ] #38 
* [ ] #41

**Comment by peterhuene** [comment]
Oh that's annoying, it didn't keep the description I did in the draft project item when it converted to an issue.

GitHub's project feature is a little under-baked 😭.

**Comment by calvinrp** [comment]
Cleaning up old issues
