### ISSUE TITLE
Story: publishing packages to the registry

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/registry#12]
[Story link](https://github.com/bytecodealliance/SIG-Registries/blob/main/docs/user-stories.md#publishing-components-g-n-p)

This is a story issue to track the overall progress towards achieving a user story.

Tasks:

* [x] #31 
* [ ] #32 
* [ ] #37 
* [ ] #41
* [ ] #45

**Comment by calvinrp** [comment]
Cleaning up old issues
