### ISSUE TITLE
Story: authoring a component in Rust using the registry

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/registry#13]
[Story link](https://github.com/bytecodealliance/SIG-Registries/blob/main/docs/user-stories.md#authoring-components-a-b-c-i)

This is a story issue to track the overall progress towards achieving a user story.

Tasks:

* [x] #31 
* [ ] #33 
* [ ] #34 
* [ ] #38 
* [ ] #39 
* [x] #40 
* [x] #42 
* [x] #43 
* [x] #44

**Comment by calvinrp** [comment]
Cleaning up old issues
