### ISSUE TITLE
Log length `u64` vs `u32`

### ISSUE THREAD

**Issue by calvinrp** [bytecodealliance/registry#135]
Should [`log_length` in `MapCheckpoint`](https://github.com/bytecodealliance/registry/blob/f0e45fc765e24e7bb6671f568ee4d3f80a723689/crates/protocol/src/registry.rs#L15) be changed to a `u64`. If so, that change needs to be propagated through the datastore schemas.

From my understanding, `log_length` represents the total count of all records since the beginning of that registry. It could grow to be a very large number over time.

**Comment by Kylebrown9** [comment]
I believe at the time we chose `u32` somewhat arbitrarily. I believe @lann said at the time that upgrading the size is easy from a protobuf version / compatibility perspective so we didn't worry about it too much.

**Comment by lann** [comment]
Yeah I think that specific type is an implementation detail that can change whenever if it needs to. You can see right below that its converted to u64 for singing purposes: https://github.com/bytecodealliance/registry/blob/f0e45fc765e24e7bb6671f568ee4d3f80a723689/crates/protocol/src/registry.rs#L26

**Comment by calvinrp** [comment]
That makes sense. I'll close this issue.
