### ISSUE TITLE
Improve `protoc` user experience

### ISSUE THREAD

**Issue by Kylebrown9** [bytecodealliance/registry#140]
Potential users of cargo component are getting scared off by the build error requiring them to install protoc even though it's stated as an installation requirement and we provide a detailed error message about what's missing/wrong.

We should consider
a. providing an even more detailed error message that gives exact install instructions,
b. providing a simplified way to install the required protoc,
c. vendor protoc so that an external installation isn't needed,
d. or automatically install protoc for users.

**Comment by lann** [comment]
e. Commit the protoc-generated Rust.

...which is the most common solution to this problem.

**Comment by Kylebrown9** [comment]
After doing some more research, there's another simpler option.
f. use [`protox`](https://github.com/andrewhickman/protox) which is "A pure-rust protobuf compiler, designed for use with prost-build" to avoid needing actual `protoc`
