### ISSUE TITLE
Change Protobuf to encode hash values as bytes instead of string

### ISSUE THREAD

**Issue by calvinrp** [bytecodealliance/registry#151]

**Comment by lann** [comment]
We should consider dropping the hash algo from PackageRelease entirely. If it ended up being needed in the future it could be backward-compatibly added by specifying e.g. "if the algo isn't specified, use this log's init.hash_algorithm".

**Comment by calvinrp** [comment]
Withdrawing this proposed change. After discussions and code review, it isn't worth the effort to make the change.
