### ISSUE TITLE
`accept_ranges` field is not camelCased in JSON

### ISSUE THREAD

**Issue by calvinrp** [bytecodealliance/registry#221]
Serde `rename_all` as an attribute on an enum is renaming all the variants of the enum, not all the fields of those variants.

[Missing `rename_all` on enum variant](https://github.com/bytecodealliance/registry/blob/release-0.2/crates/api/src/v1/mod.rs#L16)

**Comment by lann** [comment]
We're going to use this as an exercise in change management for `0.2.x` releases.

As a general approach, I'm proposing:

1. a serde `alias` for the corrected name; this gives clients forward-compatibility
2. wait a release
3. change the field default to the correct name, alias the incorrect name
4. wait (a couple releases? until `0.3`?)
5. drop the alias

**Comment by calvinrp** [comment]
Merged in #253
