### ISSUE TITLE
local infra setup doesn't work automatically

### ISSUE THREAD

**Issue by lu4p** [bytecodealliance/registry#240]
I've got this running locally now, but I needed to change these two lines in the Dockerfile to get it to run:

```Dockerfile
RUN cargo install --locked diesel_cli --no-default-features --features postgres
ENTRYPOINT [ "/usr/local/bin/diesel", "migration", "run", "--migration-dir", "./src/datastore/postgres/migrations", "--database-url", "postgres://postgres:5b79d985-ece8-4345-8f40-bd8ff630a715@db:5432/warg_registry"]
```

Setting `DATABASE_URL` in the .env file didn't work.

**Comment by calvinrp** [comment]
I recommend following the directions here: https://github.com/bytecodealliance/registry/blob/main/crates/server/README.md

The other infra directory setup may not be correctly wired up and isn't being used.

**Comment by calvinrp** [comment]
This was revised in #282
