### ISSUE TITLE
Provide optional warning messages on the `/v1/fetch/logs` response

### ISSUE THREAD

**Issue by calvinrp** [bytecodealliance/registry#261]
When the registry wants to provide warnings to the client CLI, such as for deprecated packages, we need to add an optional field in the fetch logs response.

[See the code for FetchLogsResponse](https://github.com/bytecodealliance/registry/blob/main/crates/api/src/v1/fetch.rs#L42-L55)
```rust
pub struct FetchLogsResponse {
    /// Whether there are more records to fetch.
    #[serde(default)]
    pub more: bool,
    /// The operator records appended since the last known operator record.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub operator: Vec<PublishedRecord>,
    /// The package records appended since last known package record ids.
    #[serde(default, skip_serializing_if = "IndexMap::is_empty")]
    pub packages: IndexMap<LogId, Vec<PublishedRecord>>,
}
```

Could add a field
```rust
    /// Optional warning message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub warning: Option<String>,
```

Then in the client CLI, print the warning message, if present.
[See](https://github.com/bytecodealliance/registry/blob/main/crates/client/src/lib.rs#L620-L636)

**Comment by lann** [comment]
I would give this a little more structure as future-proofing, e.g.
```json
"warnings": [{"message": "..."}]
```

**Comment by RobbieMcKinstry** [comment]
LGTM! I'm happy to tackle this one. I'll put something together in a few hours. 👍🏻
