### ISSUE TITLE
Breaking change in 0.4.2

### ISSUE THREAD

**Issue by kajacx** [bytecodealliance/registry#274]
Hello, `cargo install cargo-component` is currently not working because of breaking changes in `warg-client` and `warg-protocol` in version `v0.4.2`, see [here](https://github.com/bytecodealliance/cargo-component/issues/293) for more detail.

Since the version of the wasm registry crates is already at 0.5.0 I don't know if it is worth to "fix" the older 0.4.x version, not that it is possible to fix in any meaningful way anyway, but I just wanted to let you know.

**Comment by FrankReh** [comment]
One way to get cargo-component installed now is
```rust
cargo install cargo-component --locked
```
This was figured out yesterday and the installation instructions have been updated as a result I think.

**Comment by calvinrp** [comment]
We are trying to find someone with permission to yank the warg releases. The releases should have increased the minor version since there changes to the exported functions.

Also, https://github.com/bytecodealliance/cargo-component/pull/288 would fix.

**Comment by calvinrp** [comment]
Released `0.4.4` as a re-release of `0.4.1` that reverts the breaking changes. Also, we are in the progress of yanking `0.4.2` and `0.4.3` on crates.

**Comment by kajacx** [comment]
> Released `0.4.4` as a re-release of `0.4.1` that reverts the breaking changes.

That's what I thought initially, but that introduces breaking changes to people who used `0.4.2` or `0.4.3`, but since those versions are pretty new *and* are getting yanked, it should be (mostly) fine. Thanks for taking care of it!
