### ISSUE TITLE
Refactor some names

### ISSUE THREAD

**Issue by Kylebrown9** [bytecodealliance/registry#94]
We've come up with some clearer/better names for types the more we use them. Now we just need to swap them out.

* `Validator` in e.g. `PackageValidator` -> `State`
  * While you can validate using these, the struct itself really represents the state of the validator.
*  `DynHash`/`Hash<D>` -> `AnyHash`/`Hash<D>`
   * The "static vs. dynamic" naming here is accurate in some sense, but is confusing especially with the use of `dyn` as a keyword for things. The real distinction is that `AnyHash` can hold a hash of any allowed algorithm type whereas `Hash<D>` identifies a singular algorithm in its type.

**Comment by peterhuene** [comment]
Second half of this issue is fixed with #126.

**Comment by calvinrp** [comment]
> For renaming `Validator`, how about `LogState`?

Sounds fine to me
