### ISSUE TITLE
Recommend API routes have `v1` prefix

### ISSUE THREAD

**Issue by kriswuollett** [bytecodealliance/registry#99]
Some guides [recommend that APIs are versioned](https://cloud.google.com/apis/design/versioning) so that breaking changes can be introduced later. Recommend that start with a `v1` prefix. Currently there is no prefix:

https://github.com/bytecodealliance/registry/blob/eee527f91d96776b58cf4631911eecabdee7512e/crates/server/src/lib.rs#L234-L237

**Comment by Kylebrown9** [comment]
We're still likely to make many breaking changes before we get to anything resembling a `1.0` / `v1`.
So this makes sense, but we'll need to somehow make it clear to people that `v1` is WIP and not stable.
